#ifndef CONFIGURATION_H_
#define CONFIGURATION_H_

// System configuration
extern SYSTEM_CONFIGURATION_TYPE SYSTEM_CONFIGURATION;

// MODULE module configuration
extern MODULE_CONFIGURATION_TYPE MODULE_MODULE_CONFIGURATION;

#endif
