// Module includes
#include "module_module.h"

// PARTITION1 partition process configuration
static PROCESS_CONFIGURATION_TYPE PARTITION1_PARTITION_PROCESS_CONFIGURATION[2] = {

/*PROCESS1 process*/{
/*NAME*/(PROCESS_NAME_TYPE) "PROCESS1",
/*PROCESS_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x80033000,
/*PROCESS_STACK_SIZE*/(SIZE_TYPE) 0x00001000,
/*PORT_PROCESS_CONFIGURATION*/(SYSTEM_ADDRESS_TYPE) null },

/*PROCESS2 process*/{
/*NAME*/(PROCESS_NAME_TYPE) "PROCESS2",
/*PROCESS_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x80035000,
/*PROCESS_STACK_SIZE*/(SIZE_TYPE) 0x00001000,
/*PORT_PROCESS_CONFIGURATION*/(SYSTEM_ADDRESS_TYPE) null } };

// PARTITION1 partition configuration schedule window
static PARTITION_CONFIGURATION_SCHEDULE_WINDOW_TYPE PARTITION1_PARTITION_CONFIGURATION_SCHEDULE_WINDOW[2] = {
/*1*/{/*START*/(SYSTEM_TIME_TYPE) 0, /*DURATION*/(SYSTEM_TIME_TYPE) 25000000, /*PERIOD_START*/(BOOLEAN_TYPE) true },
/*2*/{/*START*/(SYSTEM_TIME_TYPE) 50000000, /*DURATION*/(SYSTEM_TIME_TYPE) 25000000, /*PERIOD_START*/(BOOLEAN_TYPE) true } };

// PARTITION1 partition configuration schedule
static PARTITION_CONFIGURATION_SCHEDULE_TYPE PARTITION1_PARTITION_CONFIGURATION_SCHEDULE = {
/*PERIOD*/(SYSTEM_TIME_TYPE) 50000000,
/*DURATION*/(SYSTEM_TIME_TYPE) 25000000,
/*SCHEDULE_WINDOW_SIZE*/(SIZE_TYPE) 2,
/*SCHEDULE_WINDOW*/PARTITION1_PARTITION_CONFIGURATION_SCHEDULE_WINDOW };

// PARTITION2 partition configuration schedule window
static PARTITION_CONFIGURATION_SCHEDULE_WINDOW_TYPE PARTITION2_PARTITION_CONFIGURATION_SCHEDULE_WINDOW[2] = {
/*1*/{/*START*/(SYSTEM_TIME_TYPE) 25000000, /*DURATION*/(SYSTEM_TIME_TYPE) 10000000, /*PERIOD_START*/(BOOLEAN_TYPE) true },
/*2*/{/*START*/(SYSTEM_TIME_TYPE) 75000000, /*DURATION*/(SYSTEM_TIME_TYPE) 10000000, /*PERIOD_START*/(BOOLEAN_TYPE) true } };

// PARTITION2 partition configuration schedule
static PARTITION_CONFIGURATION_SCHEDULE_TYPE PARTITION2_PARTITION_CONFIGURATION_SCHEDULE = {
/*PERIOD*/(SYSTEM_TIME_TYPE) 50000000,
/*DURATION*/(SYSTEM_TIME_TYPE) 10000000,
/*SCHEDULE_WINDOW_SIZE*/(SIZE_TYPE) 2,
/*SCHEDULE_WINDOW*/PARTITION2_PARTITION_CONFIGURATION_SCHEDULE_WINDOW };

// PARTITION3 partition configuration schedule window
static PARTITION_CONFIGURATION_SCHEDULE_WINDOW_TYPE PARTITION3_PARTITION_CONFIGURATION_SCHEDULE_WINDOW[1] = {
/*1*/{/*START*/(SYSTEM_TIME_TYPE) 35000000, /*DURATION*/(SYSTEM_TIME_TYPE) 10000000, /*PERIOD_START*/(BOOLEAN_TYPE) true } };

// PARTITION3 partition configuration schedule
static PARTITION_CONFIGURATION_SCHEDULE_TYPE PARTITION3_PARTITION_CONFIGURATION_SCHEDULE = {
/*PERIOD*/(SYSTEM_TIME_TYPE) 100000000,
/*DURATION*/(SYSTEM_TIME_TYPE) 10000000,
/*SCHEDULE_WINDOW_SIZE*/(SIZE_TYPE) 1,
/*SCHEDULE_WINDOW*/PARTITION3_PARTITION_CONFIGURATION_SCHEDULE_WINDOW };

// Partition configuration
static PARTITION_CONFIGURATION_TYPE MODULE_MODULE_PARTITION_CONFIGURATION[3] = {

/*PARTITION1 partition*/{
/*EXTERNAL_IDENTIFIER*/(PARTITION_ID_TYPE) 1,
/*NAME*/(PARTITION_NAME_TYPE) "PARTITION1",
/*MAXIMUM_PROCESS_COUNT*/(SIZE_TYPE) 2,
/*MAXIMUM_ERRORSTATUS_COUNT*/(SIZE_TYPE) 4,
/*MAXIMUM_SAMPLINGPORT_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_QUEUINGPORT_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_BUFFER_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_BLACKBOARD_COUNT*/(SIZE_TYPE) 1,
/*MAXIMUM_SEMAPHORE_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_EVENT_COUNT*/(SIZE_TYPE) 0,
/*PARTITION_CODE_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x80027000,
/*PARTITION_CODE_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_DATA_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x80028000,
/*PARTITION_DATA_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_DATA_IMAGE_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x8033C000,
/*PARTITION_DATA_IMAGE_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_HEAP_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x80139000,
/*PARTITION_HEAP_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_DEFAULTPROCESS_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x80032000,
/*PARTITION_DEFAULTPROCESS_STACK_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_ERRORHANDLER_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) null,
/*PARTITION_ERRORHANDLER_STACK_SIZE*/(SIZE_TYPE) null,
/*PARTITION_HMCALLBACK_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) null,
/*PARTITION_HMCALLBACK_STACK_SIZE*/(SIZE_TYPE) null,
/*PARTITION_CONFIGURATION_SCHEDULE*/&PARTITION1_PARTITION_CONFIGURATION_SCHEDULE,
/*PARTITION_CONFIGURATION_HEALTHMONITORING*/(PARTITION_CONFIGURATION_HEALTHMONITORING_TYPE *) null,
/*PROCESS_CONFIGURATION_SIZE*/(SIZE_TYPE) 2,
/*PROCESS_CONFIGURATION*/PARTITION1_PARTITION_PROCESS_CONFIGURATION,
/*PORT_PARTITION_CONFIGURATION*/(SYSTEM_ADDRESS_TYPE) null },

/*PARTITION2 partition*/{
/*EXTERNAL_IDENTIFIER*/(PARTITION_ID_TYPE) 2,
/*NAME*/(PARTITION_NAME_TYPE) "PARTITION2",
/*MAXIMUM_PROCESS_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_ERRORSTATUS_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_SAMPLINGPORT_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_QUEUINGPORT_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_BUFFER_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_BLACKBOARD_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_SEMAPHORE_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_EVENT_COUNT*/(SIZE_TYPE) 0,
/*PARTITION_CODE_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x80029000,
/*PARTITION_CODE_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_DATA_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x8002A000,
/*PARTITION_DATA_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_DATA_IMAGE_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x8033D000,
/*PARTITION_DATA_IMAGE_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_HEAP_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x8013A000,
/*PARTITION_HEAP_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_DEFAULTPROCESS_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x80036000,
/*PARTITION_DEFAULTPROCESS_STACK_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_ERRORHANDLER_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) null,
/*PARTITION_ERRORHANDLER_STACK_SIZE*/(SIZE_TYPE) null,
/*PARTITION_HMCALLBACK_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) null,
/*PARTITION_HMCALLBACK_STACK_SIZE*/(SIZE_TYPE) null,
/*PARTITION_CONFIGURATION_SCHEDULE*/&PARTITION2_PARTITION_CONFIGURATION_SCHEDULE,
/*PARTITION_CONFIGURATION_HEALTHMONITORING*/(PARTITION_CONFIGURATION_HEALTHMONITORING_TYPE *) null,
/*PROCESS_CONFIGURATION_SIZE*/(SIZE_TYPE) 0,
/*PROCESS_CONFIGURATION*/(PROCESS_CONFIGURATION_TYPE *) null,
/*PORT_PARTITION_CONFIGURATION*/(SYSTEM_ADDRESS_TYPE) null },

/*PARTITION3 partition*/{
/*EXTERNAL_IDENTIFIER*/(PARTITION_ID_TYPE) 3,
/*NAME*/(PARTITION_NAME_TYPE) "PARTITION3",
/*MAXIMUM_PROCESS_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_ERRORSTATUS_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_SAMPLINGPORT_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_QUEUINGPORT_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_BUFFER_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_BLACKBOARD_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_SEMAPHORE_COUNT*/(SIZE_TYPE) 0,
/*MAXIMUM_EVENT_COUNT*/(SIZE_TYPE) 0,
/*PARTITION_CODE_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x8002B000,
/*PARTITION_CODE_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_DATA_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x8002C000,
/*PARTITION_DATA_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_DATA_IMAGE_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x8033E000,
/*PARTITION_DATA_IMAGE_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_HEAP_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x8013B000,
/*PARTITION_HEAP_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_DEFAULTPROCESS_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x80037000,
/*PARTITION_DEFAULTPROCESS_STACK_SIZE*/(SIZE_TYPE) 0x00001000,
/*PARTITION_ERRORHANDLER_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) null,
/*PARTITION_ERRORHANDLER_STACK_SIZE*/(SIZE_TYPE) null,
/*PARTITION_HMCALLBACK_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) null,
/*PARTITION_HMCALLBACK_STACK_SIZE*/(SIZE_TYPE) null,
/*PARTITION_CONFIGURATION_SCHEDULE*/&PARTITION3_PARTITION_CONFIGURATION_SCHEDULE,
/*PARTITION_CONFIGURATION_HEALTHMONITORING*/(PARTITION_CONFIGURATION_HEALTHMONITORING_TYPE *) null,
/*PROCESS_CONFIGURATION_SIZE*/(SIZE_TYPE) 0,
/*PROCESS_CONFIGURATION*/(PROCESS_CONFIGURATION_TYPE *) null,
/*PORT_PARTITION_CONFIGURATION*/(SYSTEM_ADDRESS_TYPE) null } };

// Port MODULE module configuration
static PORT_MODULE_CONFIGURATION_TYPE MODULE_PORT_MODULE_CONFIGURATION = {
/*VECTORTABLE_ADDRESS*/(portADDRESS) 0x40300000,
/*VECTORTABLE_SIZE*/(portSIZE) 0x00001000,
/*MODULE_FLTRANSLATIONTABLE_ADDRESS*/(portADDRESS) 0x8013C000,
/*MODULE_FLTRANSLATIONTABLE_SIZE*/(portSIZE) 0x00100000,
/*MODULE_SLTRANSLATIONTABLE_ADDRESS*/(portADDRESS) 0x8023C000,
/*MODULE_SLTRANSLATIONTABLE_SIZE*/(portSIZE) 0x00100000,
/*MODULE_GLOBAL_FLTRANSLATIONTABLE_ADDRESS (Filled by the operating system)*/(portUINTBASE *) null,
/*MODULE_NETWORK_PHYSICAL_ADDRESS*/{ 0x00, 0x00, 0x00, 0x01, 0x01, 0x01, 1, 1, 16, 16 } };

// MODULE module configuration
MODULE_CONFIGURATION_TYPE MODULE_MODULE_CONFIGURATION = {
/*MAXIMUM_PARTITION_COUNT*/(SIZE_TYPE) 3,
/*MODULE_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x8002E000,
/*MODULE_STACK_SIZE*/(SIZE_TYPE) 0x00004000,
/*MODULE_CODE_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x80025000,
/*MODULE_CODE_SIZE*/(SIZE_TYPE) 0x00001000,
/*MODULE_DATA_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x80026000,
/*MODULE_DATA_SIZE*/(SIZE_TYPE) 0x00001000,
/*MODULE_HEAP_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x80039000,
/*MODULE_HEAP_SIZE*/(SIZE_TYPE) 0x00100000,
/*MODULE_HMCALLBACK_STACK_ADDRESS*/(SYSTEM_ADDRESS_TYPE) null,
/*MODULE_HMCALLBACK_STACK_SIZE*/(SIZE_TYPE) null,
/*MAJORFRAME_DURATION*/(SYSTEM_TIME_TYPE) 100000000,
/*MODULE_CONFIGURATION_CONNECTIONTABLE*/(MODULE_CONFIGURATION_CONNECTIONTABLE_TYPE *) null,
/*MODULE_CONFIGURATION_HEALTHMONITORING*/(MODULE_CONFIGURATION_HEALTHMONITORING_TYPE *) null,
/*PARTITION_CONFIGURATION_SIZE*/(SIZE_TYPE) 3,
/*PARTITION_CONFIGURATION*/MODULE_MODULE_PARTITION_CONFIGURATION,
/*PORT_MODULE_CONFIGURATION*/(SYSTEM_ADDRESS_TYPE) &MODULE_PORT_MODULE_CONFIGURATION };

// Port system configuration
static PORT_SYSTEM_CONFIGURATION_TYPE PORT_SYSTEM_CONFIGURATION = {
/*STACK_AREA_START_ADDRESS*/(portADDRESS) 0x8002D000,
/*STACK_AREA_END_ADDRESS*/(portADDRESS) 0x80039000,
/*PERIPHERALS_ADDRESS*/(portADDRESS) 0x44000000,
/*PERIPHERALS_SIZE*/(portSIZE) 0x3C000000,
/*SYSTEM_BOOT_ADDRESS*/(portADDRESS) 0x80000000,
/*SYSTEM_BOOT_SIZE*/(portSIZE) 0x00001000 };

// System configuration
SYSTEM_CONFIGURATION_TYPE SYSTEM_CONFIGURATION = {
/*SYSTEM_CODE_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x80001000,
/*SYSTEM_CODE_SIZE*/(SIZE_TYPE) 0x00020000,
/*SYSTEM_DATA_ADDRESS*/(SYSTEM_ADDRESS_TYPE) 0x80021000,
/*SYSTEM_DATA_SIZE*/(SIZE_TYPE) 0x00004000,
/*SYSTEM_CONFIGURATION_HEALTHMONITORING*/(SYSTEM_CONFIGURATION_HEALTHMONITORING_TYPE *) null,
/*PORT_SYSTEM_CONFIGURATION*/(SYSTEM_ADDRESS_TYPE) &PORT_SYSTEM_CONFIGURATION };
