#ifndef CONFIGURATION_H_
#define CONFIGURATION_H_

// Module configuration
extern MODULE_CONFIGURATION_TYPE MODULE_CONFIGURATION;

// System configuration
extern SYSTEM_CONFIGURATION_TYPE SYSTEM_CONFIGURATION;

#endif
