// Module include
#include "module_module.h"

// Configuration include
#include "configuration.h"

// SNIPPET_START GLOBAL_INCLUDES
// Test include
#include "test.h"
// SNIPPET_END

// -------------------- MODULE DESCRIPTION START --------------------
// SNIPPET_START MODULE_MODULE_DESCRIPTION
// SNIPPET_END
// -------------------- MODULE DESCRIPTION END --------------------

// SNIPPET_START MODULE_MODULE_INCLUDES
// SNIPPET_END

// Core #0 entry point
void (*ENTRYPOINT_CORE0)(void) = MODULE_MODULE_DEFAULTPARTITION;

// Core #0 module configuration
MODULE_CONFIGURATION_TYPE *MODULE_CONFIGURATION_CORE0 = &MODULE_MODULE_CONFIGURATION;

// PARTITION1 partition attributes
static PARTITION_ATTRIBUTE_TYPE PARTITION1_PARTITION_ATTRIBUTE = {
/*NAME*/(PARTITION_NAME_TYPE) "PARTITION1",
/*ENTRY_POINT*/(SYSTEM_ADDRESS_TYPE) &PARTITION1_DEFAULTPROCESS,
/*STACK_SIZE*/(STACK_SIZE_TYPE) 256,
/*SYSTEMPARTITION*/(BOOLEAN_TYPE) false };

// PARTITION1 partition identifier
static PARTITION_ID_TYPE PARTITION1_PARTITION_ID;

// PARTITION2 partition attributes
static PARTITION_ATTRIBUTE_TYPE PARTITION2_PARTITION_ATTRIBUTE = {
/*NAME*/(PARTITION_NAME_TYPE) "PARTITION2",
/*ENTRY_POINT*/(SYSTEM_ADDRESS_TYPE) &PARTITION2_DEFAULTPROCESS,
/*STACK_SIZE*/(STACK_SIZE_TYPE) 256,
/*SYSTEMPARTITION*/(BOOLEAN_TYPE) false };

// PARTITION2 partition identifier
static PARTITION_ID_TYPE PARTITION2_PARTITION_ID;

// PARTITION3 partition attributes
static PARTITION_ATTRIBUTE_TYPE PARTITION3_PARTITION_ATTRIBUTE = {
/*NAME*/(PARTITION_NAME_TYPE) "PARTITION3",
/*ENTRY_POINT*/(SYSTEM_ADDRESS_TYPE) &PARTITION3_DEFAULTPROCESS,
/*STACK_SIZE*/(STACK_SIZE_TYPE) 256,
/*SYSTEMPARTITION*/(BOOLEAN_TYPE) false };

// PARTITION3 partition identifier
static PARTITION_ID_TYPE PARTITION3_PARTITION_ID;

// SNIPPET_START MODULE_MODULE_GLOBAL_DEFINITIONS
// SNIPPET_END

// SNIPPET_START MODULE_MODULE_GLOBAL_VARIABLES
// SNIPPET_END

// SNIPPET_START MODULE_MODULE_FUNCTIONS
// SNIPPET_END

// MODULE module default partition
void MODULE_MODULE_DEFAULTPARTITION(void) {
	RETURN_CODE_TYPE RETURN_CODE;
	// SNIPPET_START MODULE_MODULE_DEFAULTPARTITION_VARIABLES
	portBYTE COMMAND;
	// SNIPPET_END

	// Starts module up
	STARTUP_MODULE(&RETURN_CODE);
	if (RETURN_CODE != NO_ERROR) {
		// SNIPPET_START STARTUP_MODULE_ERROR_HANDLING_CODE
		while (true) {
		}
		// SNIPPET_END
	}

	// Creates PARTITION1 partition
	CREATE_PARTITION(&PARTITION1_PARTITION_ATTRIBUTE, &PARTITION1_PARTITION_ID, &RETURN_CODE);
	if (RETURN_CODE != NO_ERROR) {
		// SNIPPET_START CREATE_PARTITION_ERROR_HANDLING_CODE
		while (true) {
		}
		// SNIPPET_END
	}

	// Creates PARTITION2 partition
	CREATE_PARTITION(&PARTITION2_PARTITION_ATTRIBUTE, &PARTITION2_PARTITION_ID, &RETURN_CODE);
	if (RETURN_CODE != NO_ERROR) {
		// SNIPPET_START CREATE_PARTITION_ERROR_HANDLING_CODE
		while (true) {
		}
		// SNIPPET_END
	}

	// Creates PARTITION3 partition
	CREATE_PARTITION(&PARTITION3_PARTITION_ATTRIBUTE, &PARTITION3_PARTITION_ID, &RETURN_CODE);
	if (RETURN_CODE != NO_ERROR) {
		// SNIPPET_START CREATE_PARTITION_ERROR_HANDLING_CODE
		while (true) {
		}
		// SNIPPET_END
	}

	// SNIPPET_START MODULE_MODULE_DEFAULTPARTITION_INITIALIZATION
	// SNIPPET_END

	// Sets module mode
	SET_MODULE_MODE(NORMAL, &RETURN_CODE);
	if (RETURN_CODE != NO_ERROR) {
		// SNIPPET_START SET_MODULE_MODE_ERROR_HANDLING_CODE
		while (true) {
		}
		// SNIPPET_END
	}

	// Start of idle partition

	// SNIPPET_START MODULE_MODULE_IDLEPARTITION_INITIALIZATION
	// SNIPPET_END

	// Main loop
	while (true) {

		// SNIPPET_START MODULE_MODULE_IDLEPARTITION_CODE
		// Sets LEDs pattern
		TEST_LED1_OFF();
		TEST_LED2_OFF();

		// Handles reset command
		if ((CONSOLE_READ_BYTE(&COMMAND)) && (COMMAND == 0)) {
			PORT_RESTARTMODULE();
		}
		// SNIPPET_END
	}
}
