#ifndef ARINC653_HEALTHMONITORING_H_
#define ARINC653_HEALTHMONITORING_H_

// Run system error action method
void RUN_SYSTEM_ERROR_ACTION(BOOLEAN_TYPE ENTERCORE, BOOLEAN_TYPE YIELD, SYSTEM_STATE_TYPE SYSTEM_STATE, ERROR_IDENTIFIER_TYPE ERROR_IDENTIFIER);

// Run module error action method
void RUN_MODULE_ERROR_ACTION(BOOLEAN_TYPE ENTERCORE, BOOLEAN_TYPE YIELD, SYSTEM_STATE_TYPE SYSTEM_STATE, ERROR_IDENTIFIER_TYPE ERROR_IDENTIFIER);

// Stop module health monitoring callback method
void STOP_MODULE_HEALTHMONITORINGCALLBACK(void);

// Run partition error action method
void RUN_PARTITION_ERROR_ACTION(BOOLEAN_TYPE ENTERCORE, BOOLEAN_TYPE YIELD, SYSTEM_STATE_TYPE SYSTEM_STATE, ERROR_IDENTIFIER_TYPE ERROR_IDENTIFIER);

// Stop partition health monitoring callback method
void STOP_PARTITION_HEALTHMONITORINGCALLBACK(void);

// Raise error method
void RAISE_ERROR(BOOLEAN_TYPE ENTERCORE, BOOLEAN_TYPE YIELD, BOOLEAN_TYPE SYSTEM_PARTITION_CONTEXT, SYSTEM_STATE_TYPE SYSTEM_STATE, ERROR_IDENTIFIER_TYPE ERROR_IDENTIFIER, ERROR_CODE_TYPE ERROR_CODE, MESSAGE_ADDR_TYPE MESSAGE_ADDR, ERROR_MESSAGE_SIZE_TYPE LENGTH, PROCESS_ID_TYPE FAILED_PROCESS_ID, SYSTEM_ADDRESS_TYPE FAILED_ADDRESS, RETURN_CODE_TYPE *RETURN_CODE);

#endif
