#ifndef ARINC653_INTERPARTITIONCOMMUNICATION_SAMPLINGPORT_H_
#define ARINC653_INTERPARTITIONCOMMUNICATION_SAMPLINGPORT_H_

// Partition sampling port identifier getter
void GET_PARTITION_SAMPLING_PORT_ID(PARTITION_ID_TYPE PARTITION_ID, SAMPLING_PORT_NAME_TYPE SAMPLING_PORT_NAME, SAMPLING_PORT_ID_TYPE *SAMPLING_PORT_ID, RETURN_CODE_TYPE *RETURN_CODE);

// Write partition sampling message method
void WRITE_PARTITION_SAMPLING_MESSAGE(PARTITION_ID_TYPE PARTITION_ID, SAMPLING_PORT_ID_TYPE SAMPLING_PORT_ID, MESSAGE_ADDR_TYPE MESSAGE_ADDR, MESSAGE_SIZE_TYPE LENGTH, RETURN_CODE_TYPE *RETURN_CODE);

// Read partition sampling message method
void READ_PARTITION_SAMPLING_MESSAGE(PARTITION_ID_TYPE PARTITION_ID, SAMPLING_PORT_ID_TYPE SAMPLING_PORT_ID, MESSAGE_ADDR_TYPE MESSAGE_ADDR, MESSAGE_SIZE_TYPE *LENGTH, BOOLEAN_TYPE PEEK, RETURN_CODE_TYPE *RETURN_CODE);

#endif
