#ifndef ARINC653_CONFIGURATION_H_
#define ARINC653_CONFIGURATION_H_

// System configuration
extern SYSTEM_CONFIGURATION_TYPE SYSTEM_CONFIGURATION;

// Module configuration
extern MODULE_CONFIGURATION_TYPE MODULE_CONFIGURATION;

// Get partition configuration method
PARTITION_CONFIGURATION_TYPE *CONFIGURATION_GETPARTITIONCONFIGURATION(PARTITION_NAME_TYPE PARTITION_NAME);

// Get process configuration method
PROCESS_CONFIGURATION_TYPE *CONFIGURATION_GETPROCESSCONFIGURATION(PARTITION_CONFIGURATION_TYPE *PARTITION_CONFIGURATION, PROCESS_NAME_TYPE PROCESS_NAME);

#endif
