#ifndef ARINC653_PROCESSMANAGEMENT_H_
#define ARINC653_PROCESSMANAGEMENT_H_

// Wait resource method
void WAIT_RESOURCE(PARTITION_ID_TYPE PARTITION_ID, PROCESS_ID_TYPE PROCESS_ID, priorityqueueRECORD *REC_RESOURCE, SYSTEM_TIME_TYPE TIME_OUT, RETURN_CODE_TYPE *RETURN_CODE);

// Signal resource method
void SIGNAL_RESOURCE(PARTITION_ID_TYPE PARTITION_ID, priorityqueueRECORD *REC_RESOURCE, BOOLEAN_TYPE RESCHEDULE, RETURN_CODE_TYPE *RETURN_CODE);

#endif
