#ifndef ARINC653_PARTITIONMANAGEMENT_H_
#define ARINC653_PARTITIONMANAGEMENT_H_

// Partition internal identifier getter
void GET_PARTITION_INTERNAL_IDENTIFIER(PARTITION_ID_TYPE PARTITION_EXTERNAL_IDENTIFIER, PARTITION_ID_TYPE *PARTITION_INTERNAL_IDENTIFIER, RETURN_CODE_TYPE *RETURN_CODE);

#endif
