#ifndef ARINC653_INTERPARTITIONCOMMUNICATION_QUEUINGPORT_H_
#define ARINC653_INTERPARTITIONCOMMUNICATION_QUEUINGPORT_H_

// Partition queuing port identifier getter
void GET_PARTITION_QUEUING_PORT_ID(PARTITION_ID_TYPE PARTITION_ID, QUEUING_PORT_NAME_TYPE QUEUING_PORT_NAME, QUEUING_PORT_ID_TYPE *QUEUING_PORT_ID, RETURN_CODE_TYPE *RETURN_CODE);

// Send queuing message method
void SEND_PARTITION_QUEUING_MESSAGE(PARTITION_ID_TYPE PARTITION_ID, QUEUING_PORT_ID_TYPE QUEUING_PORT_ID, MESSAGE_ADDR_TYPE MESSAGE_ADDR, MESSAGE_SIZE_TYPE LENGTH, RETURN_CODE_TYPE *RETURN_CODE);

// Receive partition queuing message method
void RECEIVE_PARTITION_QUEUING_MESSAGE(PARTITION_ID_TYPE PARTITION_ID, QUEUING_PORT_ID_TYPE QUEUING_PORT_ID, MESSAGE_ADDR_TYPE MESSAGE_ADDR, MESSAGE_SIZE_TYPE *LENGTH, BOOLEAN_TYPE PEEK, RETURN_CODE_TYPE *RETURN_CODE);

#endif
