#ifndef ARINC653_CLOCK_H_
#define ARINC653_CLOCK_H_

// Startup macro
#define CLOCK_STARTUP(); {\
	/*Starts up*/\
	MODULE_INFORMATION.MAJOR_FRAME_START = 0;\
	MODULE_INFORMATION.MAJOR_FRAME_TIME = 0;\
	MODULE_INFORMATION.NEXT_MAJOR_FRAME_START = MODULE_INFORMATION.MODULE_CONFIGURATION->MAJORFRAME_DURATION;\
}

// Tick window macro
#define CLOCK_TICKWINDOW(); {\
	/*Counts time*/\
	MODULE_INFORMATION.MAJOR_FRAME_TIME += PORT_TICKWINDOW;\
}

// Tick major frame macro
#define CLOCK_TICKMAJORFRAME(); {\
	/*Counts major frame time*/\
	MODULE_INFORMATION.MAJOR_FRAME_START += MODULE_INFORMATION.MODULE_CONFIGURATION->MAJORFRAME_DURATION;\
	/*Resets major frame time*/\
	MODULE_INFORMATION.MAJOR_FRAME_TIME = 0;\
	/*Calculates next major frame start*/\
	MODULE_INFORMATION.NEXT_MAJOR_FRAME_START = MODULE_INFORMATION.MAJOR_FRAME_START + MODULE_INFORMATION.MODULE_CONFIGURATION->MAJORFRAME_DURATION;\
}

// System time getter macro
#define CLOCK_GETSYSTEMTIME() (MODULE_INFORMATION.MAJOR_FRAME_START + MODULE_INFORMATION.MAJOR_FRAME_TIME)

#endif
