typedef unsigned int UWORD32;

void Disable_Watchdog();
void AM335x_Beaglebone_Initialization();
void GetInputClockFrequency();
void ARM_Turbo_Config();
void ARM_OPP120_Config();
void ARM_OPP100_Config();
void MPU_PLL_Config(UWORD32 CLKIN,UWORD32 N,UWORD32 M,UWORD32 M2);
void CORE_PLL_Config(UWORD32 CLKIN,UWORD32 N,UWORD32 M,UWORD32 M4,UWORD32 M5,UWORD32 M6);
void DDR_PLL_Config(UWORD32 CLKIN,UWORD32 N,UWORD32 M,UWORD32 M2);
void PER_PLL_Config(UWORD32 CLKIN,UWORD32 N,UWORD32 M,UWORD32 M2);
void DISP_PLL_Config(UWORD32 CLKIN,UWORD32 N,UWORD32 M,UWORD32 M2);
void DDR2_EMIF_Config();
void PHY_Config_CMD();
void PHY_Config_DATA();
void EMIF_PRCM_CLK_ENABLE();
void VTP_Enable();
void OSC_32KHz();
void L3_CLK();
void DDR_PHY_Clock();
void PER_Clock();
void LCD_Clock();
void set_CLKOUT2(UWORD32 mode);
void enable_SYS_CLKOUT2();
void Device_Type();
