// General includes
#include "test.h"

// Hardware includes
#include "hw_control_AM335x.h"
#include "soc_AM335x.h"
#include "hw_types.h"

// Test startup method
unsigned char TEST_STARTUP(void) {
	// Enables GPIO module clock
	GPIO1ModuleClkConfig();

	// Selects pins for use
	HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_A(5)) = CONTROL_CONF_MUXMODE(7);
	HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_A(6)) = CONTROL_CONF_MUXMODE(7);
	HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_A(7)) = CONTROL_CONF_MUXMODE(7);
	HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_A(8)) = CONTROL_CONF_MUXMODE(7);
	HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(2)) = CONTROL_CONF_MUXMODE(7);
	HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(6)) = CONTROL_CONF_MUXMODE(7);
	HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(13)) = CONTROL_CONF_MUXMODE(7);

	// Enables GPIO module
	GPIOModuleEnable(SOC_GPIO_1_REGS);

	// Resets GPIO module
	GPIOModuleReset(SOC_GPIO_1_REGS);

	// Sets pins mode
	GPIODirModeSet(SOC_GPIO_1_REGS, 21, GPIO_DIR_OUTPUT);
	GPIODirModeSet(SOC_GPIO_1_REGS, 22, GPIO_DIR_OUTPUT);
	GPIODirModeSet(SOC_GPIO_1_REGS, 23, GPIO_DIR_OUTPUT);
	GPIODirModeSet(SOC_GPIO_1_REGS, 24, GPIO_DIR_OUTPUT);
	GPIODirModeSet(SOC_GPIO_1_REGS, 2, GPIO_DIR_OUTPUT);
	GPIODirModeSet(SOC_GPIO_1_REGS, 6, GPIO_DIR_OUTPUT);
	GPIODirModeSet(SOC_GPIO_1_REGS, 13, GPIO_DIR_OUTPUT);

	// Accesses the GPIO controller's pins
	TEST_LED1_ON();
	TEST_LED2_ON();

	// Accesses the GPIO controller's pins
	TEST_LED1_OFF();
	TEST_LED2_OFF();
	return 1;
}
